### ISSUE TITLE
Error: n_other is not a list

### ISSUE THREAD

**Issue by gustavdelius** [baldrech/mizerEvolution#2]
Currently `evoParams()` returns an invalid MizerSim object in which the `n_other` slot is not a list array but a numeric array. In the new version of mizer which checks validity of objects more often, this leads to an error when trying to plot the MizerSim object.

**Comment by baldrech** [comment]
`finalTouch()` was the issue, it now output `n_other` in the same format as `MizerSim()`. However it won't handle a specific `n_other` input from a user. I need to work out an example of `n_other` to see how it behaves.
