### ISSUE TITLE
"subscript out of bounds" error in `evoProject()`

### ISSUE THREAD

**Issue by gustavdelius** [baldrech/mizerEvolution#3]
Occasionally the randomisation in `evoProject()` works out in a way that produces a "subscript out of bounds" error. The following reproduces the problem on my machine:
```
params <- evoParams(no_sp = 5)
set.seed(0)
sim <- evoProject(params = params, mutation = 1)
```

**Comment by baldrech** [comment]
The error was produced when a new mutant appeared at the last time step. This is not possible anymore.
